// <auto-generated />
using System;
using LVB.Portal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LVB.Portal.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LVB.Portal.Domain.Entities.ApiKey", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                b.Property<DateTime?>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                b.Property<string>("KeyHash").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("key_hash");
                b.Property<DateTime?>("LastUsedAt").HasColumnType("timestamp with time zone").HasColumnName("last_used_at");
                b.Property<string>("Name").HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("name");
                b.HasKey("Id").HasName("pk_api_keys");
                b.ToTable("api_keys");
            });

            modelBuilder.Entity("LVB.Portal.Domain.Entities.Department", b =>
            {
                b.Property<string>("Code").HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("code");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                b.Property<string>("Name").HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("name");
                b.HasKey("Code").HasName("pk_departments");
                b.ToTable("departments");
            });
#pragma warning restore 612, 618
        }
    }
}
